/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package personeltakipoto;

import java.awt.Color;
import javax.swing.BorderFactory;

/**
 *
 * @author sabir
 */
public class anaForm extends javax.swing.JFrame {

     private personelYonetim personelYonetim = new personelYonetim();
    
     private void listele() {
        anaformtablo.setModel(personelYonetim.Listele());
        anaformtablo.getColumnModel().getColumn(0).setMinWidth(0);
        anaformtablo.getColumnModel().getColumn(0).setMaxWidth(0);
        
        anaformtablo.getColumnModel().getColumn(13).setMinWidth(0);
        anaformtablo.getColumnModel().getColumn(13).setMaxWidth(0);
        
        
        anaformtablo.getColumnModel().getColumn(6).setMinWidth(0);
        anaformtablo.getColumnModel().getColumn(6).setMaxWidth(0);
        
        
        anaformtablo.getColumnModel().getColumn(7).setMinWidth(0);
        anaformtablo.getColumnModel().getColumn(7).setMaxWidth(0);
     
     }
     
    public anaForm() {
        initComponents();
        
        listele();
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblcikis = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        anaformtablo = new javax.swing.JTable();
        lblcikis1 = new javax.swing.JLabel();
        lblcikis2 = new javax.swing.JLabel();
        lblcikis3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblcikis.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcikis.setForeground(new java.awt.Color(255, 255, 255));
        lblcikis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcikis.setText("ÇIKIŞ");
        lblcikis.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        lblcikis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblcikisMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcikisMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcikisMouseExited(evt);
            }
        });
        jPanel1.add(lblcikis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 190, 80));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PERSONEL");
        jLabel1.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 190, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ANAFORM");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 190, 80));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("KULLANICILAR");
        jLabel3.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 190, 80));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 1, 0, new java.awt.Color(255, 255, 255)));
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 190, 40));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 190, 450));

        jButton4.setText("PERSONEL");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 86));

        jButton5.setText("PERSONEL");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 150, 86));

        anaformtablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(anaformtablo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 0, 800, 400));

        lblcikis1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcikis1.setForeground(new java.awt.Color(255, 255, 255));
        lblcikis1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcikis1.setText("ÇIKIŞ");
        lblcikis1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcikis1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcikis1MouseExited(evt);
            }
        });
        getContentPane().add(lblcikis1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 80));

        lblcikis2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcikis2.setForeground(new java.awt.Color(255, 255, 255));
        lblcikis2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcikis2.setText("ÇIKIŞ");
        lblcikis2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcikis2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcikis2MouseExited(evt);
            }
        });
        getContentPane().add(lblcikis2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 80));

        lblcikis3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblcikis3.setForeground(new java.awt.Color(255, 255, 255));
        lblcikis3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblcikis3.setText("ÇIKIŞ");
        lblcikis3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblcikis3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblcikis3MouseExited(evt);
            }
        });
        getContentPane().add(lblcikis3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 190, 80));

        jPanel2.setBackground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("PERSONEL TAKİP SİSTEMİ @ 2021");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 780, 50));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 400, 800, 50));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("jLabel4");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 190, 60));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("jLabel4");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 190, 60));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("jLabel4");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 4, 190, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void lblcikisMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikisMouseEntered
        
    }//GEN-LAST:event_lblcikisMouseEntered

    private void lblcikisMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikisMouseExited
    
        
    }//GEN-LAST:event_lblcikisMouseExited

    private void lblcikis1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikis1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcikis1MouseEntered

    private void lblcikis1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikis1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcikis1MouseExited

    private void lblcikis2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikis2MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcikis2MouseEntered

    private void lblcikis2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikis2MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcikis2MouseExited

    private void lblcikis3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikis3MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcikis3MouseEntered

    private void lblcikis3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikis3MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_lblcikis3MouseExited

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        
         personelFormu personelformu = new personelFormu();
        personelformu.show();
        
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
         
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
         kullaniciFormu kullaniciformu = new kullaniciFormu();
        kullaniciformu.show();
    }//GEN-LAST:event_jLabel3MouseClicked

    private void lblcikisMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblcikisMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblcikisMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(anaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new anaForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable anaformtablo;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblcikis;
    private javax.swing.JLabel lblcikis1;
    private javax.swing.JLabel lblcikis2;
    private javax.swing.JLabel lblcikis3;
    // End of variables declaration//GEN-END:variables
}
